
title: "CSCI 2200, Fall '21"
remote_theme: pmarsceill/just-the-docs

description: Website for  csci2200 (Algorithms), Fall 21,  Bowdoin College
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bowdoin-csci2200.github.io" # the base hostname & protocol for your site, e.g. http://example.com

